// <auto-generated />
using System;
using EY.TalentSurfer.Support.Persistence.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EY.TalentSurfer.Support.Persistence.Sql.Migrations
{
    [DbContext(typeof(TalentSurferContext))]
    [Migration("20191121145205_OpportuntyNewFields")]
    partial class OpportuntyNewFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EY.TalentSurfer.Domain.Certainty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Certainty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 813, DateTimeKind.Unspecified).AddTicks(1794), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "1. Lost",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "0%"
                        },
                        new
                        {
                            Id = 2,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 813, DateTimeKind.Unspecified).AddTicks(4113), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "2. Forecast",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "20%"
                        },
                        new
                        {
                            Id = 3,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 813, DateTimeKind.Unspecified).AddTicks(4136), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "3. Under Discussion",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "40%"
                        },
                        new
                        {
                            Id = 4,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 813, DateTimeKind.Unspecified).AddTicks(4139), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "4. Proposal Sent",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "60%"
                        },
                        new
                        {
                            Id = 5,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 813, DateTimeKind.Unspecified).AddTicks(4142), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "5. SOW Sent",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "80%"
                        },
                        new
                        {
                            Id = 6,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 813, DateTimeKind.Unspecified).AddTicks(4145), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "6. SOW Approved",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "100%"
                        });
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 807, DateTimeKind.Unspecified).AddTicks(3804), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Anywhere",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 807, DateTimeKind.Unspecified).AddTicks(8525), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Anywhere LATAM",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 807, DateTimeKind.Unspecified).AddTicks(8571), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Anywhere INDIA",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 807, DateTimeKind.Unspecified).AddTicks(8575), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "US",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 807, DateTimeKind.Unspecified).AddTicks(8578), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Anywhere ARG",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 807, DateTimeKind.Unspecified).AddTicks(8581), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Anywhere CO",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 807, DateTimeKind.Unspecified).AddTicks(8584), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Pune",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 807, DateTimeKind.Unspecified).AddTicks(8586), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bangalore",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 9,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 807, DateTimeKind.Unspecified).AddTicks(8589), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "CABA",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 10,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 807, DateTimeKind.Unspecified).AddTicks(8592), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "CBA",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 11,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 807, DateTimeKind.Unspecified).AddTicks(8594), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "RO",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 12,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 807, DateTimeKind.Unspecified).AddTicks(8597), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "MDZ",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 13,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 807, DateTimeKind.Unspecified).AddTicks(8600), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bogota",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 14,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 807, DateTimeKind.Unspecified).AddTicks(8603), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Medellin",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.Opportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CertaintyId");

                    b.Property<string>("Contact");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("EyId");

                    b.Property<string>("HiringManager");

                    b.Property<int?>("MapId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.Property<string>("Name");

                    b.Property<string>("OriginalOpptCopy");

                    b.Property<string>("Owner");

                    b.Property<int?>("PrimaryLocationId");

                    b.Property<string>("Product");

                    b.Property<int?>("ProjectId");

                    b.Property<string>("ProposalFolder");

                    b.Property<string>("RequestedByEmail");

                    b.Property<string>("RequestedByName");

                    b.Property<DateTime>("RequestedOn");

                    b.Property<int?>("ServiceLineId");

                    b.Property<int>("Sow");

                    b.Property<DateTime>("StartDate");

                    b.Property<int?>("StatusId");

                    b.HasKey("Id");

                    b.HasIndex("CertaintyId");

                    b.HasIndex("MapId");

                    b.HasIndex("PrimaryLocationId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ServiceLineId");

                    b.HasIndex("StatusId");

                    b.ToTable("Opportunity");
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.OpportunityLocation", b =>
                {
                    b.Property<int>("OpportunityId");

                    b.Property<int>("LocationId");

                    b.HasKey("OpportunityId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("OpportunityLocation");
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.HasKey("Id");

                    b.ToTable("Position");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(4702), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "** Not Needed **",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6524), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = ".Net Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6544), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "BI Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6547), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "BPM Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6549), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Business Analyst",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6552), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Business Intelligence",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6555), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Data Architect",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6558), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Data Scientist",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 9,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6560), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "DBA",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 10,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6563), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "DevOps/Cloud Engineer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 11,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6566), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Java Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 12,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6568), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Mobile Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 13,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6571), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Performance Test Engineer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 14,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6574), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Project Manager",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 15,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6576), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Python Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 16,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6579), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "QC Analyst",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 17,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6582), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Salesforce Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 18,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6584), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Scrum Master",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 19,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6587), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Service Now Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 20,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6590), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sharepoint Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 21,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6592), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "SOA Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 22,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6595), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "SQL Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 23,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6598), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Test Automation Engineer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 24,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6600), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tech Manager",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 25,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6603), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "SME",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 26,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6606), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "User Experience Designer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 27,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6608), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Visual Designer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 28,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 809, DateTimeKind.Unspecified).AddTicks(6611), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Web UI Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.PositionEY", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PositionEY");
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.PositionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.HasKey("Id");

                    b.ToTable("PositionStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 812, DateTimeKind.Unspecified).AddTicks(4204), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "** Not Needed **",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 812, DateTimeKind.Unspecified).AddTicks(6149), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "1. No Candidates",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 812, DateTimeKind.Unspecified).AddTicks(6169), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "2. Internal FIT",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 812, DateTimeKind.Unspecified).AddTicks(6173), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "3. Canfirmed (NOW)",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 812, DateTimeKind.Unspecified).AddTicks(6176), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "4. Confirmed (Future)",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.Seniority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.HasKey("Id");

                    b.ToTable("Seniority");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 811, DateTimeKind.Unspecified).AddTicks(7265), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "** Not Needed **",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 811, DateTimeKind.Unspecified).AddTicks(9050), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Trainee",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 811, DateTimeKind.Unspecified).AddTicks(9070), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Junior",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 811, DateTimeKind.Unspecified).AddTicks(9074), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Junior Adv",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 811, DateTimeKind.Unspecified).AddTicks(9077), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "SSr",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 811, DateTimeKind.Unspecified).AddTicks(9080), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "SSr Adv",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 811, DateTimeKind.Unspecified).AddTicks(9083), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Senior",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 811, DateTimeKind.Unspecified).AddTicks(9086), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "SD / Level 2",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 9,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 811, DateTimeKind.Unspecified).AddTicks(9088), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Architect / Level 3",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 10,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 811, DateTimeKind.Unspecified).AddTicks(9091), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Level 4",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 12,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 811, DateTimeKind.Unspecified).AddTicks(9094), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Level 5",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.ServiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.HasKey("Id");

                    b.ToTable("ServiceLine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 810, DateTimeKind.Unspecified).AddTicks(7906), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Platform",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 810, DateTimeKind.Unspecified).AddTicks(9637), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "ATTG",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 810, DateTimeKind.Unspecified).AddTicks(9655), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "GTP",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 810, DateTimeKind.Unspecified).AddTicks(9658), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Business",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.Sow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Sow");
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 810, DateTimeKind.Unspecified).AddTicks(1409), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "1. Wating for Feedback",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 810, DateTimeKind.Unspecified).AddTicks(3138), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "2. On Hold",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 810, DateTimeKind.Unspecified).AddTicks(3158), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "3. Lost",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 11, 21, 14, 52, 4, 810, DateTimeKind.Unspecified).AddTicks(3162), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "4. Won",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<int>("Status");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.Opportunity", b =>
                {
                    b.HasOne("EY.TalentSurfer.Domain.Certainty", "Certainty")
                        .WithMany()
                        .HasForeignKey("CertaintyId");

                    b.HasOne("EY.TalentSurfer.Domain.Opportunity", "Map")
                        .WithMany()
                        .HasForeignKey("MapId");

                    b.HasOne("EY.TalentSurfer.Domain.Location", "PrimaryLocation")
                        .WithMany()
                        .HasForeignKey("PrimaryLocationId");

                    b.HasOne("EY.TalentSurfer.Domain.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("EY.TalentSurfer.Domain.ServiceLine", "ServiceLine")
                        .WithMany()
                        .HasForeignKey("ServiceLineId");

                    b.HasOne("EY.TalentSurfer.Domain.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.OpportunityLocation", b =>
                {
                    b.HasOne("EY.TalentSurfer.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EY.TalentSurfer.Domain.Opportunity", "Opportunity")
                        .WithMany("AdditionalOpportunityLocations")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("EY.TalentSurfer.Domain.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("EY.TalentSurfer.Domain.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EY.TalentSurfer.Domain.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("EY.TalentSurfer.Domain.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
