// <auto-generated />
using System;
using EY.TalentSurfer.Support.Persistence.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EY.TalentSurfer.Support.Persistence.Sql.Migrations
{
    [DbContext(typeof(TalentSurferContext))]
    [Migration("20191021125435_InitialDataLoad")]
    partial class InitialDataLoad
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EY.TalentSurfer.Domain.BusinessUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.Property<int>("SortOrder");

                    b.HasKey("Id");

                    b.ToTable("BusinessUnit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 940, DateTimeKind.Unspecified).AddTicks(3283), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Platform",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 940, DateTimeKind.Unspecified).AddTicks(3306), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "ATTG",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 940, DateTimeKind.Unspecified).AddTicks(3310), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "GTP",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 940, DateTimeKind.Unspecified).AddTicks(3313), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Business",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.Certainty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.Property<int>("SortOrder");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Certainty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 942, DateTimeKind.Unspecified).AddTicks(9918), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "1. Lost",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 1,
                            Value = "0%"
                        },
                        new
                        {
                            Id = 2,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 942, DateTimeKind.Unspecified).AddTicks(9945), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "2. Forecast",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 2,
                            Value = "20%"
                        },
                        new
                        {
                            Id = 3,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 942, DateTimeKind.Unspecified).AddTicks(9949), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "3. Under Discussion",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 3,
                            Value = "40%"
                        },
                        new
                        {
                            Id = 4,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 942, DateTimeKind.Unspecified).AddTicks(9954), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "4. Proposal Sent",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 4,
                            Value = "60%"
                        },
                        new
                        {
                            Id = 5,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 942, DateTimeKind.Unspecified).AddTicks(9957), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "5. SOW Sent",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 5,
                            Value = "80%"
                        },
                        new
                        {
                            Id = 6,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 942, DateTimeKind.Unspecified).AddTicks(9960), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "6. SOW Approved",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 6,
                            Value = "100%"
                        });
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.Property<int>("SortOrder");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 936, DateTimeKind.Unspecified).AddTicks(7738), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Anywhere",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 936, DateTimeKind.Unspecified).AddTicks(8878), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Anywhere LATAM",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 936, DateTimeKind.Unspecified).AddTicks(8893), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Anywhere INDIA",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 936, DateTimeKind.Unspecified).AddTicks(8898), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "US",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 936, DateTimeKind.Unspecified).AddTicks(8902), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Anywhere ARG",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 936, DateTimeKind.Unspecified).AddTicks(8905), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Anywhere CO",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 936, DateTimeKind.Unspecified).AddTicks(8908), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Pune",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 936, DateTimeKind.Unspecified).AddTicks(8912), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bangalore",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 936, DateTimeKind.Unspecified).AddTicks(8915), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "CABA",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 936, DateTimeKind.Unspecified).AddTicks(8918), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "CBA",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 936, DateTimeKind.Unspecified).AddTicks(8922), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "RO",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 936, DateTimeKind.Unspecified).AddTicks(8925), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "MDZ",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 13,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 936, DateTimeKind.Unspecified).AddTicks(8928), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bogota",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 14,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 936, DateTimeKind.Unspecified).AddTicks(8931), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Medellin",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 14
                        });
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.Property<int>("SortOrder");

                    b.HasKey("Id");

                    b.ToTable("Position");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(181), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "** Not Needed **",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(205), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = ".Net Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(209), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "BI Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(213), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "BPM Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(216), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Business Analyst",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(220), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Business Intelligence",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(223), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Data Architect",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(226), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Data Scientist",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(229), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "DBA",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(232), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "DevOps/Cloud Engineer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(235), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Java Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(239), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Mobile Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 13,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(242), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Performance Test Engineer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 14,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(245), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Project Manager",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 14
                        },
                        new
                        {
                            Id = 15,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(248), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Python Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 15
                        },
                        new
                        {
                            Id = 16,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(251), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "QC Analyst",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 16
                        },
                        new
                        {
                            Id = 17,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(255), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Salesforce Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 17
                        },
                        new
                        {
                            Id = 18,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(258), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Scrum Master",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 18
                        },
                        new
                        {
                            Id = 19,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(261), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Service Now Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 19
                        },
                        new
                        {
                            Id = 20,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(264), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sharepoint Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 21,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(268), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "SOA Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 21
                        },
                        new
                        {
                            Id = 22,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(271), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "SQL Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 22
                        },
                        new
                        {
                            Id = 23,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(274), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Test Automation Engineer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 23
                        },
                        new
                        {
                            Id = 24,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(277), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tech Manager",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 24
                        },
                        new
                        {
                            Id = 25,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(280), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "SME",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 25
                        },
                        new
                        {
                            Id = 26,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(284), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "User Experience Designer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 26
                        },
                        new
                        {
                            Id = 27,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(287), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Visual Designer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 27
                        },
                        new
                        {
                            Id = 28,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(290), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Web UI Developer",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 28
                        });
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.PositionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.Property<int>("SortOrder");

                    b.HasKey("Id");

                    b.ToTable("PositionStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 942, DateTimeKind.Unspecified).AddTicks(1372), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "** Not Needed **",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 942, DateTimeKind.Unspecified).AddTicks(1394), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "1. No Candidates",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 942, DateTimeKind.Unspecified).AddTicks(1399), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "2. Internal FIT",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 942, DateTimeKind.Unspecified).AddTicks(1402), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "3. Canfirmed (NOW)",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 942, DateTimeKind.Unspecified).AddTicks(1406), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "4. Confirmed (Future)",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.Seniority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.Property<int>("SortOrder");

                    b.HasKey("Id");

                    b.ToTable("Seniority");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 941, DateTimeKind.Unspecified).AddTicks(3781), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "** Not Needed **",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 941, DateTimeKind.Unspecified).AddTicks(3803), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Trainee",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 941, DateTimeKind.Unspecified).AddTicks(3808), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Junior",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 941, DateTimeKind.Unspecified).AddTicks(3811), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Junior Adv",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 941, DateTimeKind.Unspecified).AddTicks(3814), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "SSr",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 941, DateTimeKind.Unspecified).AddTicks(3817), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "SSr Adv",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 941, DateTimeKind.Unspecified).AddTicks(3820), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Senior",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 941, DateTimeKind.Unspecified).AddTicks(3824), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "SD / Level 2",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 941, DateTimeKind.Unspecified).AddTicks(3827), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Architect / Level 3",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 941, DateTimeKind.Unspecified).AddTicks(3830), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Level 4",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 12,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 941, DateTimeKind.Unspecified).AddTicks(3833), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Level 5",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 12
                        });
                });

            modelBuilder.Entity("EY.TalentSurfer.Domain.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ArchivingFlag");

                    b.Property<string>("Comments");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.Property<int>("SortOrder");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(7064), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "1. Wating for Feedback",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(7089), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "2. On Hold",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(7093), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "3. Lost",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            ArchivingFlag = false,
                            CreatedBy = "Initial Data Load",
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 10, 21, 12, 54, 34, 939, DateTimeKind.Unspecified).AddTicks(7096), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "4. Won",
                            ModifiedOn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
